# Generated by Django 5.2.17 on 2026-08-22 18:49

import decimal
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0008_sitephoto_separate_business_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[
                 ('vl', 'Véhicule léger'), ('pl', 'Poids lourd')], max_length=2)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=80)),
                ('modele', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True,
                 max_length=50, verbose_name='Numéro VIN')),
                ('carburant', models.CharField(choices=[('diesel', 'Diesel'), ('essence', 'Essence'), ('electrique', 'Électrique'), (
                    'hybride', 'Hybride'), ('gaz', 'Gaz'), ('autre', 'Autre')], default='diesel', max_length=15)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_service', 'En service'), (
                    'en_entretien', 'En entretien'), ('hors_service', 'Hors service'), ('cede', 'Cédé')], default='disponible', max_length=20)),
                ('date_mise_circulation', models.DateField(blank=True, null=True)),
                ('kilometrage', models.PositiveIntegerField(default=0)),
                ('date_assurance', models.DateField(blank=True,
                 null=True, verbose_name='Échéance assurance')),
                ('date_controle_technique', models.DateField(blank=True,
                 null=True, verbose_name='Échéance contrôle technique')),
                ('prochain_entretien_date', models.DateField(blank=True, null=True)),
                ('prochain_entretien_km', models.PositiveIntegerField(
                    blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='vehicules/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='vehicules_crees', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='vehicules', to='maintenance.site')),
            ],
            options={
                'ordering': ['immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='EntretienVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(choices=[('revision', 'Révision'), ('reparation', 'Réparation'), (
                    'pneumatiques', 'Pneumatiques'), ('controle', 'Contrôle technique'), ('sinistre', 'Sinistre'), ('autre', 'Autre')], max_length=20)),
                ('date_entretien', models.DateField()),
                ('kilometrage', models.PositiveIntegerField()),
                ('prestataire', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('cout', models.DecimalField(decimal_places=2,
                 default=decimal.Decimal('0.00'), max_digits=10)),
                ('facture', models.FileField(blank=True,
                 upload_to='vehicules/factures/%Y/%m/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='entretiens_vehicules_crees', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='entretiens', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['-date_entretien', '-cree_le'],
            },
        ),
    ]
