from django.urls import path

from . import views

urlpatterns = [
    # Dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("", views.dashboard, name="home"),

    # Sites et équipements
    path("sites/", views.SiteListView.as_view(), name="site_list"),
    path("sites/creer/", views.SiteCreateView.as_view(), name="site_create"),
    path("sites/<int:pk>/modifier/",
         views.SiteUpdateView.as_view(), name="site_update"),
    path("sites/<int:pk>/supprimer/",
         views.SiteDeleteView.as_view(), name="site_delete"),
    path("sites/photos/<int:pk>/", views.site_photo_afficher,
         name="site_photo_afficher"),
    path("sites/photos/<int:pk>/supprimer/",
         views.SitePhotoDeleteView.as_view(), name="site_photo_delete"),
    path("gestion-silos/", views.GestionSilosView.as_view(),
         name="gestion_silos"),
    path("gestion-silos/cellules/creer/",
         views.CelluleGrainCreateView.as_view(), name="cellule_grain_create"),
    path("gestion-silos/cellules/<int:pk>/modifier/",
         views.CelluleGrainUpdateView.as_view(), name="cellule_grain_update"),
    path("gestion-silos/cellules/<int:pk>/",
         views.CelluleGrainDetailView.as_view(), name="cellule_grain_detail"),
    path("gestion-silos/cellules/<int:pk>/relever/",
         views.cellule_grain_relever, name="cellule_grain_relever"),
    path("gestion-silos/stockages-a-plat/creer/",
         views.StockageAPlatCreateView.as_view(), name="stockage_a_plat_create"),
    path("gestion-silos/stockages-a-plat/<int:pk>/modifier/",
         views.StockageAPlatUpdateView.as_view(), name="stockage_a_plat_update"),
    path("gestion-silos/stockages-a-plat/<int:pk>/",
         views.StockageAPlatDetailView.as_view(), name="stockage_a_plat_detail"),
    path("gestion-silos/stockages-a-plat/<int:pk>/relever/",
         views.stockage_a_plat_relever, name="stockage_a_plat_relever"),
    path("gestion-silos/releves/<int:pk>/modifier/",
         views.releve_cellule_update, name="releve_cellule_update"),
    path("gestion-silos/grains/creer/",
         views.TypeGrainCreateView.as_view(), name="type_grain_create"),
    path("gestion-silos/grains/<int:pk>/modifier/",
         views.TypeGrainUpdateView.as_view(), name="type_grain_update"),
    path("equipements/", views.EquipementListView.as_view(),
         name="equipement_list"),
    path("equipements/creer/", views.EquipementCreateView.as_view(),
         name="equipement_create"),
    path("equipements/<int:pk>/modifier/",
         views.EquipementUpdateView.as_view(), name="equipement_update"),
    path("equipements/<int:pk>/supprimer/",
         views.EquipementDeleteView.as_view(), name="equipement_delete"),
    path("equipements/<int:pk>/qr/",
         views.EquipementQrView.as_view(), name="equipement_qr"),
    path("pieces/", views.PieceListView.as_view(), name="piece_list"),
    path("pieces/creer/", views.PieceCreateView.as_view(), name="piece_create"),
    path("pieces/<int:pk>/mouvement/",
         views.PieceMouvementView.as_view(), name="piece_mouvement"),

    # Pannes
    path("pannes/", views.PanneListView.as_view(), name="panne_liste"),
    path("pannes/export.csv", views.panne_export_csv, name="panne_export_csv"),
    path("pannes/creer/", views.PanneCreateView.as_view(), name="panne_creer"),
    path("pannes/<int:pk>/", views.PanneDetailView.as_view(), name="panne_detail"),
    path("pannes/<int:pk>/modifier/", views.PanneUpdateView.as_view(),
         name="panne_update"),
    path("pannes/<int:pk>/affecter/", views.panne_affecter, name="panne_affecter"),
    path("pannes/<int:pk>/priorite/", views.panne_modifier_priorite,
         name="panne_modifier_priorite"),
    path("pannes/<int:pk>/statut/", views.panne_changer_statut,
         name="panne_changer_statut"),
    path("pannes/<int:pk>/media/", views.panne_ajouter_media,
         name="panne_ajouter_media"),
    path("pannes/<int:pk>/temps-intervention/",
         views.panne_ajouter_temps_intervention,
         name="panne_ajouter_temps_intervention"),
    path("pannes/<int:pk>/temps-intervention/<int:temps_pk>/valider/",
         views.panne_valider_temps_intervention,
         name="panne_valider_temps_intervention"),
    path("pannes/<int:pk>/facture/", views.panne_ajouter_facture,
         name="panne_ajouter_facture"),
    path("pannes/<int:pk>/facture/pdf/", views.panne_ajouter_facture_pdf,
         name="panne_ajouter_facture_pdf"),
    path("pannes/<int:pk>/factures/importer/",
         views.panne_ajouter_factures, name="panne_ajouter_factures"),
    path("pannes/<int:pk>/factures/<int:facture_pk>/modifier/",
         views.panne_modifier_facture, name="panne_modifier_facture"),
    path("pannes/<int:pk>/factures/<int:facture_pk>/valider/",
         views.panne_valider_facture, name="panne_valider_facture"),
    path("pannes/<int:pk>/factures/<int:facture_pk>/supprimer/",
         views.panne_supprimer_facture, name="panne_supprimer_facture"),
    path("pannes/<int:pk>/supprimer/",
         views.PanneDeleteView.as_view(), name="panne_delete"),
    path("pannes/rapport.pdf", views.panne_report, name="panne_report"),
    path("pannes/medias/<int:pk>/supprimer/",
         views.PanneMediaDeleteView.as_view(), name="panne_media_delete"),
    path("pannes/medias/<int:pk>/telecharger/",
         views.panne_media_telecharger, name="panne_media_telecharger"),

    # Maintenances préventives
    path("preventives/", views.PreventiveListView.as_view(),
         name="preventive_liste"),
    path("preventives/calendrier/", views.PreventiveCalendarView.as_view(),
         name="preventive_calendrier"),
    path("preventives/creer/", views.PreventiveCreateView.as_view(),
         name="preventive_creer"),
    path("preventives/<int:pk>/", views.PreventiveDetailView.as_view(),
         name="preventive_detail"),
    path("preventives/<int:pk>/envoyer/",
         views.preventive_envoyer, name="preventive_envoyer"),
    path("preventives/<int:pk>/recevoir/",
         views.preventive_recevoir, name="preventive_recevoir"),
    path("preventives/<int:pk>/demarrer/",
         views.preventive_demarrer, name="preventive_demarrer"),
    path("preventives/<int:pk>/terminer/",
         views.preventive_terminer, name="preventive_terminer"),
    path("preventives/medias/<int:pk>/telecharger/",
         views.preventive_media_telecharger,
         name="preventive_media_telecharger"),
    path("preventives/<int:pk>/valider/",
         views.preventive_valider, name="preventive_valider"),
    path("preventives/<int:pk>/modifier/",
         views.PreventiveUpdateView.as_view(), name="preventive_update"),
    path("preventives/<int:pk>/statut/", views.preventive_changer_statut,
         name="preventive_changer_statut"),

    # Factures
    path("factures/", views.FactureListView.as_view(), name="facture_list"),
    path("budgets/", views.BudgetAnnuelSiteView.as_view(),
         name="budget_annuel_list"),
    path("budgets/creer/", views.BudgetAnnuelSiteCreateView.as_view(),
         name="budget_annuel_create"),
    path("factures/creer/", views.FactureCreateView.as_view(),
         name="facture_create"),
    path("factures/<int:pk>/", views.FactureDetailView.as_view(),
         name="facture_detail"),
    path("factures/<int:pk>/telecharger/", views.facture_telecharger,
         name="facture_telecharger"),
    path("factures/<int:pk>/modifier/",
         views.FactureUpdateView.as_view(), name="facture_update"),
    path("factures/<int:pk>/supprimer/",
         views.FactureDeleteView.as_view(), name="facture_delete"),
    path("factures/<int:pk>/fichier/supprimer/",
         views.FactureFileDeleteView.as_view(), name="facture_file_delete"),

    # Rapports
    path("rapports/", views.report_selector, name="report_selector"),
    path("rapports/periode/", views.PeriodReportView.as_view(),
         name="period_report"),
    path("rapports/sites/", views.SiteReportView.as_view(), name="site_report"),
    path("rapports/sites/<int:pk>/",
         views.SiteReportView.as_view(), name="site_report_detail"),
    path("rapports/mensuel/<int:year>/<int:month>/",
         views.MonthlyReportView.as_view(), name="monthly_report"),

    # Utilisateurs et profil
    path("utilisateurs/", views.UtilisateurListView.as_view(),
         name="utilisateur_list"),
    path("utilisateurs/creer/", views.UtilisateurCreateView.as_view(),
         name="utilisateur_create"),
    path("utilisateurs/<int:pk>/modifier/",
         views.UtilisateurUpdateView.as_view(), name="utilisateur_update"),
    path("utilisateurs/<int:pk>/supprimer/",
         views.UtilisateurDeleteView.as_view(), name="utilisateur_delete"),
    path("utilisateurs/<int:pk>/activation/",
         views.utilisateur_changer_activation,
         name="utilisateur_changer_activation"),
    path("profil/", views.mon_profil, name="mon_profil"),

    # Notifications
    path("notifications/", views.notifications, name="notification_liste"),
    path("notifications/<int:pk>/lue/", views.marquer_notif_lue,
         name="notification_marquer_lue"),
    path("notifications/tout-lire/", views.marquer_toutes_lues,
         name="notification_tout_lire"),
]
