# Generated by Django 5.2 on 2026-08-03 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creee_le'],
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('affectee', 'Affectée'), ('en_cours', 'En cours'), ('attente_piece', 'En attente de pièce'), ('resolue', 'Résolue'), ('cloturee', 'Clôturée')], default='nouvelle', max_length=30)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('agent_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pannes_assignees', to=settings.AUTH_USER_MODEL)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pannes_declarees', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pannes', to='maintenance.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('fournisseur', models.CharField(max_length=150)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fichier', models.FileField(blank=True, upload_to='factures/%Y/%m/')),
                ('validee', models.BooleanField(default=False)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='maintenance.panne')),
            ],
        ),
        migrations.CreateModel(
            name='PanneMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pannes/%Y/%m/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='maintenance.panne')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('maintenance', 'Agent de maintenance'), ('silo', 'Agent de silo')], default='silo', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('utilisateurs', models.ManyToManyField(blank=True, related_name='sites_autorises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='panne',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pannes', to='maintenance.site'),
        ),
        migrations.CreateModel(
            name='MaintenancePreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('echeance', models.DateTimeField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('en_cours', 'En cours'), ('a_valider', 'À valider'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('en_retard', 'En retard')], default='brouillon', max_length=30)),
                ('retour', models.TextField(blank=True)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_creees', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_recues', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_preventives', to='maintenance.equipement')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_preventives', to='maintenance.site')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='maintenance.site'),
        ),
    ]
