# Generated by Django 6.0.7 on 2026-08-03 10:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('categorie', models.CharField(choices=[('convoyeur', 'Convoyeur'), ('elevateur', 'Élévateur'), ('ventilateur', 'Ventilateur'), ('sonde', 'Sonde / Capteur'), ('electrique', 'Équipement électrique'), ('mecanique', 'Équipement mécanique'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['site', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('periodicite', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('unique', 'Unique')], default='annuelle', max_length=20)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('en_attente_pieces', 'En attente de pièces'), ('effectuee', 'Effectuée'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('en_retard', 'En retard'), ('reportee', 'Reportée'), ('partielle', 'Partielle'), ('archivee', 'Archivée')], default='planifiee', max_length=30)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('retour_intervention', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affecte_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventives_affectees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventives_creees', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventives', to='maintenance.equipement')),
            ],
            options={
                'verbose_name': 'Maintenance préventive',
                'verbose_name_plural': 'Maintenances préventives',
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=30)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('preventive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='maintenance.maintenancepreventive')),
            ],
            options={
                'verbose_name': 'Historique préventive',
                'verbose_name_plural': 'Historique préventives',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('panne', 'Panne'), ('preventive', 'Maintenance préventive'), ('facture', 'Facture'), ('retard', 'Retard'), ('affectation', 'Affectation')], max_length=20)),
                ('titre', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('affectee', 'Affectée'), ('en_cours', 'En cours'), ('en_attente_pieces', 'En attente de pièces'), ('resolue', 'Résolue'), ('fermee', 'Fermée'), ('annulee', 'Annulée')], default='nouvelle', max_length=30)),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('solution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affecte_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannes_affectees', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='maintenance.equipement')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannes_signalee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panne',
                'verbose_name_plural': 'Pannes',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=30)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='maintenance.panne')),
            ],
            options={
                'verbose_name': 'Historique panne',
                'verbose_name_plural': 'Historique pannes',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fournisseur', models.CharField(max_length=200)),
                ('type_facture', models.CharField(choices=[('pieces', 'Pièces détachées'), ('prestation', 'Prestation externe'), ('location', 'Location matériel'), ('autre', 'Autre')], default='pieces', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_facture', models.DateField()),
                ('date_echeance_paiement', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
                ('preventive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='maintenance.maintenancepreventive')),
                ('panne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='maintenance.panne')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='PanneMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pannes/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='maintenance.panne')),
            ],
            options={
                'verbose_name': 'Média panne',
                'verbose_name_plural': 'Médias pannes',
            },
        ),
        migrations.CreateModel(
            name='PreventiveMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='preventives/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('preventive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='maintenance.maintenancepreventive')),
            ],
            options={
                'verbose_name': 'Média préventive',
                'verbose_name_plural': 'Médias préventives',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('maintenance', 'Équipe maintenance'), ('silo', 'Agent silo')], default='silo', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('sites', models.ManyToManyField(blank=True, related_name='profiles', to='maintenance.site')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.AddField(
            model_name='equipement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='maintenance.site'),
        ),
    ]
