# Generated by Django 6.1 on 2026-08-20 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelPreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai', models.CharField(choices=[('j30', '30 jours avant'), ('j14', '14 jours avant'), ('j7', '7 jours avant'), ('j3', '3 jours avant'), ('j1', '1 jour avant'), ('j0', 'Le jour J')], default='j7', max_length=10)),
                ('message_personnalise', models.TextField(blank=True)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rappels_crees', to=settings.AUTH_USER_MODEL)),
                ('destinataires', models.ManyToManyField(blank=True, help_text='Responsables silo à notifier', related_name='rappels_preventive', to=settings.AUTH_USER_MODEL)),
                ('preventive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='maintenance.maintenancepreventive')),
            ],
            options={
                'verbose_name': 'Rappel préventive',
                'verbose_name_plural': 'Rappels préventives',
                'ordering': ['delai'],
            },
        ),
    ]
