# Generated by Django 5.2.17 on 2026-08-13 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, default='', max_length=30)),
                ('nouveau_statut', models.CharField(blank=True, default='', max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_pannes', to=settings.AUTH_USER_MODEL)),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='maintenance.panne')),
            ],
            options={
                'ordering': ['-creee_le'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, default='', max_length=30)),
                ('nouveau_statut', models.CharField(blank=True, default='', max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_preventives', to=settings.AUTH_USER_MODEL)),
                ('preventive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='maintenance.maintenancepreventive')),
            ],
            options={
                'ordering': ['-creee_le'],
            },
        ),
    ]
