# Generated by Django 5.2.17 on 2026-08-22 09:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_rebuild_models_from_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tarif_horaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Tarif horaire facturé par l'agent de maintenance.", max_digits=10),
        ),
        migrations.CreateModel(
            name='PanneTempsIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField(default=django.utils.timezone.localdate)),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('commentaire', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temps_interventions_realises', to=settings.AUTH_USER_MODEL)),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps_interventions', to='maintenance.panne')),
            ],
            options={
                'ordering': ['-date_intervention', '-creee_le'],
            },
        ),
    ]
