# Generated by Django 5.2.17 on 2026-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_profile_tarif_horaire_pannetempsintervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='pannetempsintervention',
            name='validee',
            field=models.BooleanField(default=False, help_text="Validé par l'administration."),
        ),
    ]
