# Generated by Django 5.2.17 on 2026-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_pannetempsintervention_validee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='statut',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('affectee', 'Affectée'), ('en_cours', 'En cours'), ('attente_piece', 'En attente de pièce'), (
                'imprevus', 'Imprévus'), ('resolue', 'Terminée'), ('cloturee', 'Archivée')], default='nouvelle', max_length=30),
        ),
    ]
