# Generated by Django 5.2.17 on 2026-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_panne_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancepreventive',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('recue', 'Reçue'), ('en_cours', 'En cours'), ('a_valider', 'À valider'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('en_retard', 'En retard'), ('effectuee', 'Terminée'), ('prise_en_compte', 'Prise en compte'), ('en_attente', 'En attente'), ('archivee', 'Archivée'), ('annulee', 'Annulée'), ('planifiee', 'Planifiée')], default='brouillon', max_length=30),
        ),
    ]
