# Generated by Django 5.2.17 on 2026-08-22 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_sitephoto_separate_business_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepreventive',
            name='periodicite',
            field=models.CharField(choices=[('ponctuelle', 'Ponctuelle'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle')], default='ponctuelle', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancepreventive',
            name='recurrence_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancepreventive',
            name='recurrence_jusquau',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancepreventive',
            name='serie_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='maintenance.maintenancepreventive'),
        ),
        migrations.AddConstraint(
            model_name='maintenancepreventive',
            constraint=models.UniqueConstraint(fields=('serie_parent', 'date_echeance'), name='unique_echeance_serie_preventive'),
        ),
    ]
