# Generated by Django 5.2.17 on 2026-08-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_maintenancepreventive_periodicite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='details_detection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facture',
            name='score_detection',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
