# Generated by Django 5.2.17 on 2026-08-24 13:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_archive_admin_validated_preventives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('poids_specifique_moyen', models.DecimalField(decimal_places=2, help_text='Poids spécifique moyen en kg/hl.',
                 max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CelluleGrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('forme', models.CharField(choices=[('ronde', 'Ronde'), ('carree', 'Carrée'), (
                    'rectangulaire', 'Rectangulaire')], default='ronde', max_length=20)),
                ('hauteur_m', models.DecimalField(decimal_places=2, max_digits=8, validators=[
                 django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='hauteur (m)')),
                ('diametre_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[
                 django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='diamètre (m)')),
                ('longueur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[
                 django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='longueur / côté (m)')),
                ('largeur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[
                 django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='largeur (m)')),
                ('capacite_m3', models.DecimalField(decimal_places=2, default=0,
                 editable=False, max_digits=10, verbose_name='capacité (m³)')),
                ('actif', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='cellules_grain', to='maintenance.site')),
            ],
            options={
                'ordering': ['site__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ReleveCellule',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('masse_estimee_tonnes', models.DecimalField(decimal_places=2, max_digits=10, validators=[
                 django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='masse estimée (t)')),
                ('poids_specifique_kg_hl', models.DecimalField(
                    decimal_places=2, editable=False, max_digits=5)),
                ('releve_le', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True)),
                ('cellule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='releves', to='maintenance.cellulegrain')),
                ('releve_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='releves_cellules', to=settings.AUTH_USER_MODEL)),
                ('type_grain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='releves', to='maintenance.typegrain')),
            ],
            options={
                'ordering': ['-releve_le', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='cellulegrain',
            constraint=models.UniqueConstraint(
                fields=('site', 'nom'), name='unique_cellule_grain_par_site'),
        ),
    ]
