# Generated by Django 5.2.17 on 2026-08-25 06:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def convertir_masses_en_toles_vides(apps, schema_editor):
    ReleveCellule = apps.get_model("maintenance", "ReleveCellule")
    releves = ReleveCellule.objects.select_related("cellule").all()
    for releve in releves.iterator():
        cellule = releve.cellule
        densite_tonnes_m3 = releve.poids_specifique_kg_hl / Decimal("100")
        if not cellule.capacite_m3 or not densite_tonnes_m3:
            continue
        volume_m3 = releve.masse_estimee_tonnes / densite_tonnes_m3
        proportion_vide = Decimal("1") - volume_m3 / cellule.capacite_m3
        nombre_toles_vides = proportion_vide * cellule.nombre_toles_hauteur
        releve.nombre_toles_vides = min(
            Decimal(cellule.nombre_toles_hauteur),
            max(Decimal("0"), nombre_toles_vides),
        ).quantize(Decimal("0.01"))
        releve.save(update_fields=["nombre_toles_vides"])


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_alter_cellulegrain_capacite_m3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellulegrain',
            name='nombre_toles_hauteur',
            field=models.PositiveSmallIntegerField(default=15, validators=[
                                                   django.core.validators.MinValueValidator(1)], verbose_name='nombre de tôles en hauteur'),
        ),
        migrations.AddField(
            model_name='relevecellule',
            name='forme_surface',
            field=models.CharField(choices=[('sortant_petit', 'Cône sortant petit'), ('sortant_moyen', 'Cône sortant moyen'), ('sortant_grand', 'Cône sortant grand'), ('aucune', 'Pas de cône'), (
                'rentrant_petit', 'Cône rentrant petit'), ('rentrant_moyen', 'Cône rentrant moyen'), ('rentrant_grand', 'Cône rentrant grand')], default='aucune', max_length=20, verbose_name='forme de la surface du grain'),
        ),
        migrations.AddField(
            model_name='relevecellule',
            name='nombre_toles_vides',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Le comptage peut être saisi par quart de tôle.', max_digits=5, validators=[
                                      django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='nombre de tôles vides'),
        ),
        migrations.RunPython(
            convertir_masses_en_toles_vides,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='relevecellule',
            name='masse_estimee_tonnes',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[
                                      django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='masse estimée (t)'),
        ),
    ]
