# Generated by Django 5.2.17 on 2026-08-25 13:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def reprendre_grain_des_releves(apps, schema_editor):
    CelluleGrain = apps.get_model("maintenance", "CelluleGrain")
    ReleveCellule = apps.get_model("maintenance", "ReleveCellule")
    for cellule in CelluleGrain.objects.all().iterator():
        dernier_releve = ReleveCellule.objects.filter(
            cellule_id=cellule.pk
        ).order_by("-releve_le", "-pk").first()
        if not dernier_releve:
            continue
        cellule.type_grain_id = dernier_releve.type_grain_id
        cellule.capacite_tonnes = (
            cellule.capacite_m3
            * dernier_releve.type_grain.poids_specifique_moyen
            / Decimal("100")
        ).quantize(Decimal("0.01"))
        cellule.save(update_fields=["type_grain", "capacite_tonnes"])


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_cellulegrain_nombre_toles_hauteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellulegrain',
            name='type_grain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='cellules', to='maintenance.typegrain', verbose_name='type de grain'),
        ),
        migrations.RunPython(
            reprendre_grain_des_releves,
            migrations.RunPython.noop,
        ),
    ]
