# Generated by Django 5.2.17 on 2026-08-25 15:38

from django.db import migrations, models
from decimal import Decimal, ROUND_HALF_UP


def recalculer_capacites(apps, schema_editor, inclure_grand_cone):
    CelluleGrain = apps.get_model("maintenance", "CelluleGrain")
    cellules = []
    for cellule in CelluleGrain.objects.select_related("type_grain").iterator():
        if cellule.forme == "ronde" and cellule.diametre_m:
            rayon = cellule.diametre_m / Decimal("2")
            surface_m2 = Decimal("3.141592653589793") * rayon * rayon
        elif cellule.forme == "carree" and cellule.longueur_m:
            surface_m2 = cellule.longueur_m * cellule.longueur_m
        elif cellule.longueur_m and cellule.largeur_m:
            surface_m2 = cellule.longueur_m * cellule.largeur_m
        else:
            surface_m2 = Decimal("0")

        volume_m3 = surface_m2 * cellule.hauteur_m
        if inclure_grand_cone and cellule.nombre_toles_hauteur:
            hauteur_tole_m = cellule.hauteur_m / cellule.nombre_toles_hauteur
            volume_m3 += (
                surface_m2 * hauteur_tole_m * Decimal("1.5") / Decimal("3")
            )

        cellule.capacite_m3 = volume_m3.quantize(
            Decimal("0.01"), rounding=ROUND_HALF_UP
        )
        densite = (
            cellule.type_grain.poids_specifique_moyen / Decimal("100")
            if cellule.type_grain_id
            else Decimal("0.75")
        )
        cellule.capacite_tonnes = (cellule.capacite_m3 * densite).quantize(
            Decimal("0.01"), rounding=ROUND_HALF_UP
        )
        cellules.append(cellule)

    CelluleGrain.objects.bulk_update(
        cellules, ["capacite_m3", "capacite_tonnes"]
    )


def inclure_grand_cone(apps, schema_editor):
    recalculer_capacites(apps, schema_editor, inclure_grand_cone=True)


def exclure_grand_cone(apps, schema_editor):
    recalculer_capacites(apps, schema_editor, inclure_grand_cone=False)


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_cellulegrain_type_grain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellulegrain',
            name='capacite_m3',
            field=models.DecimalField(decimal_places=2, default=0, editable=False,
                                      max_digits=10, verbose_name='capacité totale (m³)'),
        ),
        migrations.RunPython(inclure_grand_cone, exclure_grand_cone),
    ]
