# Generated by Django 5.2.17 on 2026-08-25 16:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_alter_cellulegrain_capacite_m3'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevecellule',
            name='tonnage_manuel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laissez vide pour calculer le tonnage à partir des tôles.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='tonnage manuel (t)'),
        ),
    ]
