# Generated by Django 5.2.17 on 2026-08-25 18:31

from django.db import migrations, models


def classer_cellules_sans_grain(apps, schema_editor):
    CelluleGrain = apps.get_model("maintenance", "CelluleGrain")
    CelluleGrain.objects.filter(type_grain__isnull=True).update(etat="vide")


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_relevecellule_tonnage_manuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellulegrain',
            name='etat',
            field=models.CharField(choices=[('en_service', 'En service'), ('vide', 'Vide'), (
                'reparation', 'En réparation'), ('nettoyage', 'En nettoyage')], default='en_service', max_length=20),
        ),
        migrations.RunPython(
            classer_cellules_sans_grain,
            migrations.RunPython.noop,
        ),
    ]
