# Generated by Django 5.2.17 on 2026-08-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_cellulegrain_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellulegrain',
            name='marque',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
